name = "bathcare"
compatibility_date = "2023-01-01"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "DEVICE_STATUSES"
id = "xxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
